apiVersion: v1
kind: Secret
metadata:
  name: supergraph-registry-secrets
data:
  hiveEncryptionSecret: {{ .Values.SECRETS.HIVE_ENCRYPTION_SECRET | b64enc | quote }}
  supertokensApiKey: {{ .Values.SECRETS.SUPERTOKENS_API_KEY | b64enc | quote }}
  clickhouseUser: {{ .Values.SECRETS.CLICKHOUSE_USER | b64enc | quote }}
  clickhousePassword: {{ .Values.SECRETS.CLICKHOUSE_PASSWORD | b64enc | quote }}
  redisPassword: {{ .Values.SECRETS.REDIS_PASSWORD | b64enc | quote }}
  postgresPassword: {{ .Values.SECRETS.POSTGRES_PASSWORD | b64enc | quote }}
  minioRootUser: {{ .Values.SECRETS.MINIO_ROOT_USER | b64enc | quote }}
  minioRootPassword: {{ .Values.SECRETS.MINIO_ROOT_PASSWORD | b64enc | quote }}
  cdnAuthPrivateKey: {{ .Values.SECRETS.CDN_AUTH_PRIVATEKEY | b64enc | quote }}
  compositionSecret: {{ .Values.SECRETS.COMPOSITION_SECRET | b64enc | quote }}
